"主窗口的ui文件"

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(700, 625)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(4)
        sizePolicy.setVerticalStretch(3)
        sizePolicy.setHeightForWidth(MainWindow.sizePolicy().hasHeightForWidth())
        MainWindow.setSizePolicy(sizePolicy)
        MainWindow.setMinimumSize(QtCore.QSize(700, 625))
        MainWindow.setMaximumSize(QtCore.QSize(700, 625))
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setAutoFillBackground(False)
        self.centralwidget.setStyleSheet("")
        self.centralwidget.setObjectName("centralwidget")
        self.horizontalLayout = QtWidgets.QHBoxLayout(self.centralwidget)
        self.horizontalLayout.setContentsMargins(0, 0, 0, 0)
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.team1 = QtWidgets.QWidget(self.centralwidget)
        self.team1.setEnabled(True)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team1.sizePolicy().hasHeightForWidth())
        self.team1.setSizePolicy(sizePolicy)
        self.team1.setStyleSheet("")
        self.team1.setObjectName("team1")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout(self.team1)
        self.verticalLayout_7.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_7.setSpacing(5)
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.team_member1 = QtWidgets.QWidget(self.team1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_member1.sizePolicy().hasHeightForWidth())
        self.team_member1.setSizePolicy(sizePolicy)
        self.team_member1.setStyleSheet("")
        self.team_member1.setObjectName("team_member1")
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout(self.team_member1)
        self.horizontalLayout_9.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_9.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_9.setSpacing(5)
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.touxiang1 = QtWidgets.QWidget(self.team_member1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touxiang1.sizePolicy().hasHeightForWidth())
        self.touxiang1.setSizePolicy(sizePolicy)
        self.touxiang1.setStyleSheet("")
        self.touxiang1.setObjectName("touxiang1")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.touxiang1)
        self.verticalLayout.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout.setSpacing(5)
        self.verticalLayout.setObjectName("verticalLayout")
        self.label1 = QtWidgets.QLabel(self.touxiang1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label1.sizePolicy().hasHeightForWidth())
        self.label1.setSizePolicy(sizePolicy)
        self.label1.setText("")
        self.label1.setObjectName("label1")
        self.verticalLayout.addWidget(self.label1)
        self.horizontalLayout_9.addWidget(self.touxiang1)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_9.addItem(spacerItem)
        self.operate1 = QtWidgets.QWidget(self.team_member1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operate1.sizePolicy().hasHeightForWidth())
        self.operate1.setSizePolicy(sizePolicy)
        self.operate1.setStyleSheet("")
        self.operate1.setObjectName("operate1")
        self.verticalLayout_9 = QtWidgets.QVBoxLayout(self.operate1)
        self.verticalLayout_9.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_9.setSpacing(1)
        self.verticalLayout_9.setObjectName("verticalLayout_9")
        spacerItem1 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_9.addItem(spacerItem1)
        self.anniu1 = QtWidgets.QWidget(self.operate1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anniu1.sizePolicy().hasHeightForWidth())
        self.anniu1.setSizePolicy(sizePolicy)
        self.anniu1.setStyleSheet("")
        self.anniu1.setObjectName("anniu1")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout(self.anniu1)
        self.horizontalLayout_10.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_10.setSpacing(1)
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.bt_area1 = QtWidgets.QWidget(self.anniu1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_area1.sizePolicy().hasHeightForWidth())
        self.bt_area1.setSizePolicy(sizePolicy)
        self.bt_area1.setStyleSheet("")
        self.bt_area1.setObjectName("bt_area1")
        self.verticalLayout_10 = QtWidgets.QVBoxLayout(self.bt_area1)
        self.verticalLayout_10.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_10.setSpacing(3)
        self.verticalLayout_10.setObjectName("verticalLayout_10")
        self.bt_add1 = QtWidgets.QPushButton(self.bt_area1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_add1.sizePolicy().hasHeightForWidth())
        self.bt_add1.setSizePolicy(sizePolicy)
        self.bt_add1.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_add1.setFont(font)
        self.bt_add1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_add1.setAutoFillBackground(False)
        self.bt_add1.setStyleSheet("background-color:#7fc3f2")
        self.bt_add1.setObjectName("bt_add1")
        self.verticalLayout_10.addWidget(self.bt_add1)
        self.bt_remove1 = QtWidgets.QPushButton(self.bt_area1)
        self.bt_remove1.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_remove1.sizePolicy().hasHeightForWidth())
        self.bt_remove1.setSizePolicy(sizePolicy)
        self.bt_remove1.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_remove1.setFont(font)
        self.bt_remove1.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_remove1.setAutoFillBackground(False)
        self.bt_remove1.setStyleSheet("background-color:#7fc3f2")
        self.bt_remove1.setObjectName("bt_remove1")
        self.verticalLayout_10.addWidget(self.bt_remove1)
        self.verticalLayout_10.setStretch(0, 1)
        self.verticalLayout_10.setStretch(1, 1)
        self.horizontalLayout_10.addWidget(self.bt_area1)
        self.horizontalLayout_10.setStretch(0, 4)
        self.verticalLayout_9.addWidget(self.anniu1)
        self.horizontalLayout_9.addWidget(self.operate1)
        self.horizontalLayout_9.setStretch(0, 3)
        self.horizontalLayout_9.setStretch(1, 1)
        self.horizontalLayout_9.setStretch(2, 3)
        self.verticalLayout_7.addWidget(self.team_member1)
        self.team_member2 = QtWidgets.QWidget(self.team1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_member2.sizePolicy().hasHeightForWidth())
        self.team_member2.setSizePolicy(sizePolicy)
        self.team_member2.setStyleSheet("")
        self.team_member2.setObjectName("team_member2")
        self.horizontalLayout_19 = QtWidgets.QHBoxLayout(self.team_member2)
        self.horizontalLayout_19.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_19.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_19.setSpacing(5)
        self.horizontalLayout_19.setObjectName("horizontalLayout_19")
        self.touxiang2 = QtWidgets.QWidget(self.team_member2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touxiang2.sizePolicy().hasHeightForWidth())
        self.touxiang2.setSizePolicy(sizePolicy)
        self.touxiang2.setStyleSheet("")
        self.touxiang2.setObjectName("touxiang2")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.touxiang2)
        self.verticalLayout_6.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_6.setSpacing(5)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.label2 = QtWidgets.QLabel(self.touxiang2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label2.sizePolicy().hasHeightForWidth())
        self.label2.setSizePolicy(sizePolicy)
        self.label2.setText("")
        self.label2.setObjectName("label2")
        self.verticalLayout_6.addWidget(self.label2)
        self.horizontalLayout_19.addWidget(self.touxiang2)
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_19.addItem(spacerItem2)
        self.operate2 = QtWidgets.QWidget(self.team_member2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operate2.sizePolicy().hasHeightForWidth())
        self.operate2.setSizePolicy(sizePolicy)
        self.operate2.setStyleSheet("")
        self.operate2.setObjectName("operate2")
        self.verticalLayout_19 = QtWidgets.QVBoxLayout(self.operate2)
        self.verticalLayout_19.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_19.setSpacing(1)
        self.verticalLayout_19.setObjectName("verticalLayout_19")
        spacerItem3 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_19.addItem(spacerItem3)
        self.anniu2 = QtWidgets.QWidget(self.operate2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anniu2.sizePolicy().hasHeightForWidth())
        self.anniu2.setSizePolicy(sizePolicy)
        self.anniu2.setStyleSheet("")
        self.anniu2.setObjectName("anniu2")
        self.horizontalLayout_20 = QtWidgets.QHBoxLayout(self.anniu2)
        self.horizontalLayout_20.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_20.setSpacing(1)
        self.horizontalLayout_20.setObjectName("horizontalLayout_20")
        self.bt_area2 = QtWidgets.QWidget(self.anniu2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_area2.sizePolicy().hasHeightForWidth())
        self.bt_area2.setSizePolicy(sizePolicy)
        self.bt_area2.setStyleSheet("")
        self.bt_area2.setObjectName("bt_area2")
        self.verticalLayout_20 = QtWidgets.QVBoxLayout(self.bt_area2)
        self.verticalLayout_20.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_20.setSpacing(3)
        self.verticalLayout_20.setObjectName("verticalLayout_20")
        self.bt_add2 = QtWidgets.QPushButton(self.bt_area2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_add2.sizePolicy().hasHeightForWidth())
        self.bt_add2.setSizePolicy(sizePolicy)
        self.bt_add2.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_add2.setFont(font)
        self.bt_add2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_add2.setAutoFillBackground(False)
        self.bt_add2.setStyleSheet("background-color:#7fc3f2")
        self.bt_add2.setObjectName("bt_add2")
        self.verticalLayout_20.addWidget(self.bt_add2)
        self.bt_remove2 = QtWidgets.QPushButton(self.bt_area2)
        self.bt_remove2.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_remove2.sizePolicy().hasHeightForWidth())
        self.bt_remove2.setSizePolicy(sizePolicy)
        self.bt_remove2.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_remove2.setFont(font)
        self.bt_remove2.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_remove2.setAutoFillBackground(False)
        self.bt_remove2.setStyleSheet("background-color:#7fc3f2")
        self.bt_remove2.setObjectName("bt_remove2")
        self.verticalLayout_20.addWidget(self.bt_remove2)
        self.verticalLayout_20.setStretch(0, 1)
        self.verticalLayout_20.setStretch(1, 1)
        self.horizontalLayout_20.addWidget(self.bt_area2)
        self.horizontalLayout_20.setStretch(0, 4)
        self.verticalLayout_19.addWidget(self.anniu2)
        self.horizontalLayout_19.addWidget(self.operate2)
        self.horizontalLayout_19.setStretch(0, 3)
        self.horizontalLayout_19.setStretch(1, 1)
        self.horizontalLayout_19.setStretch(2, 3)
        self.verticalLayout_7.addWidget(self.team_member2)
        self.team_member3 = QtWidgets.QWidget(self.team1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_member3.sizePolicy().hasHeightForWidth())
        self.team_member3.setSizePolicy(sizePolicy)
        self.team_member3.setStyleSheet("")
        self.team_member3.setObjectName("team_member3")
        self.horizontalLayout_17 = QtWidgets.QHBoxLayout(self.team_member3)
        self.horizontalLayout_17.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_17.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_17.setSpacing(5)
        self.horizontalLayout_17.setObjectName("horizontalLayout_17")
        self.touxiang3 = QtWidgets.QWidget(self.team_member3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touxiang3.sizePolicy().hasHeightForWidth())
        self.touxiang3.setSizePolicy(sizePolicy)
        self.touxiang3.setStyleSheet("")
        self.touxiang3.setObjectName("touxiang3")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.touxiang3)
        self.verticalLayout_5.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_5.setSpacing(5)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.label3 = QtWidgets.QLabel(self.touxiang3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label3.sizePolicy().hasHeightForWidth())
        self.label3.setSizePolicy(sizePolicy)
        self.label3.setText("")
        self.label3.setObjectName("label3")
        self.verticalLayout_5.addWidget(self.label3)
        self.horizontalLayout_17.addWidget(self.touxiang3)
        spacerItem4 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_17.addItem(spacerItem4)
        self.operate3 = QtWidgets.QWidget(self.team_member3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operate3.sizePolicy().hasHeightForWidth())
        self.operate3.setSizePolicy(sizePolicy)
        self.operate3.setStyleSheet("")
        self.operate3.setObjectName("operate3")
        self.verticalLayout_17 = QtWidgets.QVBoxLayout(self.operate3)
        self.verticalLayout_17.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_17.setSpacing(1)
        self.verticalLayout_17.setObjectName("verticalLayout_17")
        spacerItem5 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_17.addItem(spacerItem5)
        self.anniu3 = QtWidgets.QWidget(self.operate3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anniu3.sizePolicy().hasHeightForWidth())
        self.anniu3.setSizePolicy(sizePolicy)
        self.anniu3.setStyleSheet("")
        self.anniu3.setObjectName("anniu3")
        self.horizontalLayout_18 = QtWidgets.QHBoxLayout(self.anniu3)
        self.horizontalLayout_18.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_18.setSpacing(1)
        self.horizontalLayout_18.setObjectName("horizontalLayout_18")
        self.bt_area3 = QtWidgets.QWidget(self.anniu3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_area3.sizePolicy().hasHeightForWidth())
        self.bt_area3.setSizePolicy(sizePolicy)
        self.bt_area3.setStyleSheet("")
        self.bt_area3.setObjectName("bt_area3")
        self.verticalLayout_18 = QtWidgets.QVBoxLayout(self.bt_area3)
        self.verticalLayout_18.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_18.setSpacing(3)
        self.verticalLayout_18.setObjectName("verticalLayout_18")
        self.bt_add3 = QtWidgets.QPushButton(self.bt_area3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_add3.sizePolicy().hasHeightForWidth())
        self.bt_add3.setSizePolicy(sizePolicy)
        self.bt_add3.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_add3.setFont(font)
        self.bt_add3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_add3.setAutoFillBackground(False)
        self.bt_add3.setStyleSheet("background-color:#7fc3f2")
        self.bt_add3.setObjectName("bt_add3")
        self.verticalLayout_18.addWidget(self.bt_add3)
        self.bt_remove3 = QtWidgets.QPushButton(self.bt_area3)
        self.bt_remove3.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_remove3.sizePolicy().hasHeightForWidth())
        self.bt_remove3.setSizePolicy(sizePolicy)
        self.bt_remove3.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_remove3.setFont(font)
        self.bt_remove3.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_remove3.setAutoFillBackground(False)
        self.bt_remove3.setStyleSheet("background-color:#7fc3f2")
        self.bt_remove3.setObjectName("bt_remove3")
        self.verticalLayout_18.addWidget(self.bt_remove3)
        self.verticalLayout_18.setStretch(0, 1)
        self.verticalLayout_18.setStretch(1, 1)
        self.horizontalLayout_18.addWidget(self.bt_area3)
        self.horizontalLayout_18.setStretch(0, 4)
        self.verticalLayout_17.addWidget(self.anniu3)
        self.horizontalLayout_17.addWidget(self.operate3)
        self.horizontalLayout_17.setStretch(0, 3)
        self.horizontalLayout_17.setStretch(1, 1)
        self.horizontalLayout_17.setStretch(2, 3)
        self.verticalLayout_7.addWidget(self.team_member3)
        self.team_member4 = QtWidgets.QWidget(self.team1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_member4.sizePolicy().hasHeightForWidth())
        self.team_member4.setSizePolicy(sizePolicy)
        self.team_member4.setStyleSheet("")
        self.team_member4.setObjectName("team_member4")
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout(self.team_member4)
        self.horizontalLayout_13.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_13.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_13.setSpacing(5)
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.touxiang4 = QtWidgets.QWidget(self.team_member4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touxiang4.sizePolicy().hasHeightForWidth())
        self.touxiang4.setSizePolicy(sizePolicy)
        self.touxiang4.setStyleSheet("")
        self.touxiang4.setObjectName("touxiang4")
        self.verticalLayout_3 = QtWidgets.QVBoxLayout(self.touxiang4)
        self.verticalLayout_3.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_3.setSpacing(5)
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.label4 = QtWidgets.QLabel(self.touxiang4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label4.sizePolicy().hasHeightForWidth())
        self.label4.setSizePolicy(sizePolicy)
        self.label4.setText("")
        self.label4.setObjectName("label4")
        self.verticalLayout_3.addWidget(self.label4)
        self.horizontalLayout_13.addWidget(self.touxiang4)
        spacerItem6 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_13.addItem(spacerItem6)
        self.operate4 = QtWidgets.QWidget(self.team_member4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operate4.sizePolicy().hasHeightForWidth())
        self.operate4.setSizePolicy(sizePolicy)
        self.operate4.setStyleSheet("")
        self.operate4.setObjectName("operate4")
        self.verticalLayout_13 = QtWidgets.QVBoxLayout(self.operate4)
        self.verticalLayout_13.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_13.setSpacing(1)
        self.verticalLayout_13.setObjectName("verticalLayout_13")
        spacerItem7 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_13.addItem(spacerItem7)
        self.anniu4 = QtWidgets.QWidget(self.operate4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anniu4.sizePolicy().hasHeightForWidth())
        self.anniu4.setSizePolicy(sizePolicy)
        self.anniu4.setStyleSheet("")
        self.anniu4.setObjectName("anniu4")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout(self.anniu4)
        self.horizontalLayout_14.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_14.setSpacing(1)
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.bt_area4 = QtWidgets.QWidget(self.anniu4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_area4.sizePolicy().hasHeightForWidth())
        self.bt_area4.setSizePolicy(sizePolicy)
        self.bt_area4.setStyleSheet("")
        self.bt_area4.setObjectName("bt_area4")
        self.verticalLayout_14 = QtWidgets.QVBoxLayout(self.bt_area4)
        self.verticalLayout_14.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_14.setSpacing(3)
        self.verticalLayout_14.setObjectName("verticalLayout_14")
        self.bt_add4 = QtWidgets.QPushButton(self.bt_area4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_add4.sizePolicy().hasHeightForWidth())
        self.bt_add4.setSizePolicy(sizePolicy)
        self.bt_add4.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_add4.setFont(font)
        self.bt_add4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_add4.setAutoFillBackground(False)
        self.bt_add4.setStyleSheet("background-color:#7fc3f2")
        self.bt_add4.setObjectName("bt_add4")
        self.verticalLayout_14.addWidget(self.bt_add4)
        self.bt_remove4 = QtWidgets.QPushButton(self.bt_area4)
        self.bt_remove4.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_remove4.sizePolicy().hasHeightForWidth())
        self.bt_remove4.setSizePolicy(sizePolicy)
        self.bt_remove4.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_remove4.setFont(font)
        self.bt_remove4.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_remove4.setAutoFillBackground(False)
        self.bt_remove4.setStyleSheet("background-color:#7fc3f2")
        self.bt_remove4.setObjectName("bt_remove4")
        self.verticalLayout_14.addWidget(self.bt_remove4)
        self.verticalLayout_14.setStretch(0, 1)
        self.verticalLayout_14.setStretch(1, 1)
        self.horizontalLayout_14.addWidget(self.bt_area4)
        self.horizontalLayout_14.setStretch(0, 4)
        self.verticalLayout_13.addWidget(self.anniu4)
        self.horizontalLayout_13.addWidget(self.operate4)
        self.horizontalLayout_13.setStretch(0, 3)
        self.horizontalLayout_13.setStretch(1, 1)
        self.horizontalLayout_13.setStretch(2, 3)
        self.verticalLayout_7.addWidget(self.team_member4)
        self.team_member5 = QtWidgets.QWidget(self.team1)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_member5.sizePolicy().hasHeightForWidth())
        self.team_member5.setSizePolicy(sizePolicy)
        self.team_member5.setStyleSheet("")
        self.team_member5.setObjectName("team_member5")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout(self.team_member5)
        self.horizontalLayout_15.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_15.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_15.setSpacing(5)
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.touxiang5 = QtWidgets.QWidget(self.team_member5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touxiang5.sizePolicy().hasHeightForWidth())
        self.touxiang5.setSizePolicy(sizePolicy)
        self.touxiang5.setStyleSheet("")
        self.touxiang5.setObjectName("touxiang5")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.touxiang5)
        self.verticalLayout_4.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_4.setSpacing(5)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.label5 = QtWidgets.QLabel(self.touxiang5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label5.sizePolicy().hasHeightForWidth())
        self.label5.setSizePolicy(sizePolicy)
        self.label5.setText("")
        self.label5.setObjectName("label5")
        self.verticalLayout_4.addWidget(self.label5)
        self.horizontalLayout_15.addWidget(self.touxiang5)
        spacerItem8 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_15.addItem(spacerItem8)
        self.operate5 = QtWidgets.QWidget(self.team_member5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operate5.sizePolicy().hasHeightForWidth())
        self.operate5.setSizePolicy(sizePolicy)
        self.operate5.setStyleSheet("")
        self.operate5.setObjectName("operate5")
        self.verticalLayout_15 = QtWidgets.QVBoxLayout(self.operate5)
        self.verticalLayout_15.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_15.setSpacing(1)
        self.verticalLayout_15.setObjectName("verticalLayout_15")
        spacerItem9 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_15.addItem(spacerItem9)
        self.anniu5 = QtWidgets.QWidget(self.operate5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anniu5.sizePolicy().hasHeightForWidth())
        self.anniu5.setSizePolicy(sizePolicy)
        self.anniu5.setStyleSheet("")
        self.anniu5.setObjectName("anniu5")
        self.horizontalLayout_16 = QtWidgets.QHBoxLayout(self.anniu5)
        self.horizontalLayout_16.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_16.setSpacing(1)
        self.horizontalLayout_16.setObjectName("horizontalLayout_16")
        self.bt_area5 = QtWidgets.QWidget(self.anniu5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_area5.sizePolicy().hasHeightForWidth())
        self.bt_area5.setSizePolicy(sizePolicy)
        self.bt_area5.setStyleSheet("")
        self.bt_area5.setObjectName("bt_area5")
        self.verticalLayout_16 = QtWidgets.QVBoxLayout(self.bt_area5)
        self.verticalLayout_16.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_16.setSpacing(3)
        self.verticalLayout_16.setObjectName("verticalLayout_16")
        self.bt_add5 = QtWidgets.QPushButton(self.bt_area5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_add5.sizePolicy().hasHeightForWidth())
        self.bt_add5.setSizePolicy(sizePolicy)
        self.bt_add5.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_add5.setFont(font)
        self.bt_add5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_add5.setAutoFillBackground(False)
        self.bt_add5.setStyleSheet("background-color:#7fc3f2")
        self.bt_add5.setObjectName("bt_add5")
        self.verticalLayout_16.addWidget(self.bt_add5)
        self.bt_remove5 = QtWidgets.QPushButton(self.bt_area5)
        self.bt_remove5.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_remove5.sizePolicy().hasHeightForWidth())
        self.bt_remove5.setSizePolicy(sizePolicy)
        self.bt_remove5.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_remove5.setFont(font)
        self.bt_remove5.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_remove5.setAutoFillBackground(False)
        self.bt_remove5.setStyleSheet("background-color:#7fc3f2")
        self.bt_remove5.setObjectName("bt_remove5")
        self.verticalLayout_16.addWidget(self.bt_remove5)
        self.verticalLayout_16.setStretch(0, 1)
        self.verticalLayout_16.setStretch(1, 1)
        self.horizontalLayout_16.addWidget(self.bt_area5)
        self.horizontalLayout_16.setStretch(0, 4)
        self.verticalLayout_15.addWidget(self.anniu5)
        self.horizontalLayout_15.addWidget(self.operate5)
        self.horizontalLayout_15.setStretch(0, 3)
        self.horizontalLayout_15.setStretch(1, 1)
        self.horizontalLayout_15.setStretch(2, 3)
        self.verticalLayout_7.addWidget(self.team_member5)
        self.verticalLayout_7.setStretch(0, 1)
        self.verticalLayout_7.setStretch(1, 1)
        self.verticalLayout_7.setStretch(2, 1)
        self.verticalLayout_7.setStretch(3, 1)
        self.verticalLayout_7.setStretch(4, 1)
        self.horizontalLayout.addWidget(self.team1)
        self.start_panel = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_panel.sizePolicy().hasHeightForWidth())
        self.start_panel.setSizePolicy(sizePolicy)
        self.start_panel.setMinimumSize(QtCore.QSize(1, 1))
        self.start_panel.setStyleSheet("")
        self.start_panel.setObjectName("start_panel")
        self.verticalLayout_36 = QtWidgets.QVBoxLayout(self.start_panel)
        self.verticalLayout_36.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_36.setSpacing(0)
        self.verticalLayout_36.setObjectName("verticalLayout_36")
        self.widget = QtWidgets.QWidget(self.start_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget.sizePolicy().hasHeightForWidth())
        self.widget.setSizePolicy(sizePolicy)
        self.widget.setStyleSheet("")
        self.widget.setObjectName("widget")
        self.verticalLayout_12 = QtWidgets.QVBoxLayout(self.widget)
        self.verticalLayout_12.setContentsMargins(0, 5, 0, 0)
        self.verticalLayout_12.setSpacing(0)
        self.verticalLayout_12.setObjectName("verticalLayout_12")
        self.team1_leader = QtWidgets.QLabel(self.widget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team1_leader.sizePolicy().hasHeightForWidth())
        self.team1_leader.setSizePolicy(sizePolicy)
        self.team1_leader.setText("")
        self.team1_leader.setObjectName("team1_leader")
        self.verticalLayout_12.addWidget(self.team1_leader)
        self.verticalLayout_36.addWidget(self.widget)
        self.widget_2 = QtWidgets.QWidget(self.start_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_2.sizePolicy().hasHeightForWidth())
        self.widget_2.setSizePolicy(sizePolicy)
        self.widget_2.setStyleSheet("")
        self.widget_2.setObjectName("widget_2")
        self.verticalLayout_37 = QtWidgets.QVBoxLayout(self.widget_2)
        self.verticalLayout_37.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_37.setSpacing(5)
        self.verticalLayout_37.setObjectName("verticalLayout_37")
        self.widget_4 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_4.sizePolicy().hasHeightForWidth())
        self.widget_4.setSizePolicy(sizePolicy)
        self.widget_4.setStyleSheet("")
        self.widget_4.setObjectName("widget_4")
        self.verticalLayout_11 = QtWidgets.QVBoxLayout(self.widget_4)
        self.verticalLayout_11.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_11.setSpacing(0)
        self.verticalLayout_11.setObjectName("verticalLayout_11")
        self.vs_pic = QtWidgets.QLabel(self.widget_4)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.vs_pic.sizePolicy().hasHeightForWidth())
        self.vs_pic.setSizePolicy(sizePolicy)
        self.vs_pic.setText("")
        self.vs_pic.setObjectName("vs_pic")
        self.verticalLayout_11.addWidget(self.vs_pic)
        self.verticalLayout_37.addWidget(self.widget_4)
        self.widget_5 = QtWidgets.QWidget(self.widget_2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_5.sizePolicy().hasHeightForWidth())
        self.widget_5.setSizePolicy(sizePolicy)
        self.widget_5.setStyleSheet("")
        self.widget_5.setObjectName("widget_5")
        self.verticalLayout_2 = QtWidgets.QVBoxLayout(self.widget_5)
        self.verticalLayout_2.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_2.setSpacing(0)
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.start_sim = QtWidgets.QPushButton(self.widget_5)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.start_sim.sizePolicy().hasHeightForWidth())
        self.start_sim.setSizePolicy(sizePolicy)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setPointSize(15)
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.start_sim.setFont(font)
        self.start_sim.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.start_sim.setStyleSheet("background-color:#fa4c3a")
        self.start_sim.setObjectName("start_sim")
        self.verticalLayout_2.addWidget(self.start_sim)
        self.verticalLayout_37.addWidget(self.widget_5)
        self.verticalLayout_37.setStretch(0, 140)
        self.verticalLayout_37.setStretch(1, 52)
        self.verticalLayout_36.addWidget(self.widget_2)
        self.widget_3 = QtWidgets.QWidget(self.start_panel)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.widget_3.sizePolicy().hasHeightForWidth())
        self.widget_3.setSizePolicy(sizePolicy)
        self.widget_3.setStyleSheet("")
        self.widget_3.setObjectName("widget_3")
        self.verticalLayout_38 = QtWidgets.QVBoxLayout(self.widget_3)
        self.verticalLayout_38.setContentsMargins(0, 0, 0, 5)
        self.verticalLayout_38.setSpacing(0)
        self.verticalLayout_38.setObjectName("verticalLayout_38")
        self.team2_leader = QtWidgets.QLabel(self.widget_3)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team2_leader.sizePolicy().hasHeightForWidth())
        self.team2_leader.setSizePolicy(sizePolicy)
        self.team2_leader.setText("")
        self.team2_leader.setObjectName("team2_leader")
        self.verticalLayout_38.addWidget(self.team2_leader)
        self.verticalLayout_36.addWidget(self.widget_3)
        self.verticalLayout_36.setStretch(0, 1)
        self.verticalLayout_36.setStretch(1, 1)
        self.verticalLayout_36.setStretch(2, 1)
        self.horizontalLayout.addWidget(self.start_panel)
        self.team2 = QtWidgets.QWidget(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team2.sizePolicy().hasHeightForWidth())
        self.team2.setSizePolicy(sizePolicy)
        self.team2.setMinimumSize(QtCore.QSize(1, 1))
        self.team2.setStyleSheet("")
        self.team2.setObjectName("team2")
        self.verticalLayout_35 = QtWidgets.QVBoxLayout(self.team2)
        self.verticalLayout_35.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout_35.setSpacing(5)
        self.verticalLayout_35.setObjectName("verticalLayout_35")
        self.team_member6 = QtWidgets.QWidget(self.team2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_member6.sizePolicy().hasHeightForWidth())
        self.team_member6.setSizePolicy(sizePolicy)
        self.team_member6.setStyleSheet("")
        self.team_member6.setObjectName("team_member6")
        self.horizontalLayout_27 = QtWidgets.QHBoxLayout(self.team_member6)
        self.horizontalLayout_27.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_27.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_27.setSpacing(5)
        self.horizontalLayout_27.setObjectName("horizontalLayout_27")
        self.touxiang6 = QtWidgets.QWidget(self.team_member6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touxiang6.sizePolicy().hasHeightForWidth())
        self.touxiang6.setSizePolicy(sizePolicy)
        self.touxiang6.setStyleSheet("")
        self.touxiang6.setObjectName("touxiang6")
        self.verticalLayout_29 = QtWidgets.QVBoxLayout(self.touxiang6)
        self.verticalLayout_29.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_29.setSpacing(5)
        self.verticalLayout_29.setObjectName("verticalLayout_29")
        self.label6 = QtWidgets.QLabel(self.touxiang6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label6.sizePolicy().hasHeightForWidth())
        self.label6.setSizePolicy(sizePolicy)
        self.label6.setText("")
        self.label6.setObjectName("label6")
        self.verticalLayout_29.addWidget(self.label6)
        self.horizontalLayout_27.addWidget(self.touxiang6)
        spacerItem10 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_27.addItem(spacerItem10)
        self.operate6 = QtWidgets.QWidget(self.team_member6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operate6.sizePolicy().hasHeightForWidth())
        self.operate6.setSizePolicy(sizePolicy)
        self.operate6.setStyleSheet("")
        self.operate6.setObjectName("operate6")
        self.verticalLayout_30 = QtWidgets.QVBoxLayout(self.operate6)
        self.verticalLayout_30.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_30.setSpacing(1)
        self.verticalLayout_30.setObjectName("verticalLayout_30")
        spacerItem11 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_30.addItem(spacerItem11)
        self.anniu6 = QtWidgets.QWidget(self.operate6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anniu6.sizePolicy().hasHeightForWidth())
        self.anniu6.setSizePolicy(sizePolicy)
        self.anniu6.setStyleSheet("")
        self.anniu6.setObjectName("anniu6")
        self.horizontalLayout_28 = QtWidgets.QHBoxLayout(self.anniu6)
        self.horizontalLayout_28.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_28.setSpacing(1)
        self.horizontalLayout_28.setObjectName("horizontalLayout_28")
        self.bt_area6 = QtWidgets.QWidget(self.anniu6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_area6.sizePolicy().hasHeightForWidth())
        self.bt_area6.setSizePolicy(sizePolicy)
        self.bt_area6.setStyleSheet("")
        self.bt_area6.setObjectName("bt_area6")
        self.verticalLayout_31 = QtWidgets.QVBoxLayout(self.bt_area6)
        self.verticalLayout_31.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_31.setSpacing(3)
        self.verticalLayout_31.setObjectName("verticalLayout_31")
        self.bt_add6 = QtWidgets.QPushButton(self.bt_area6)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_add6.sizePolicy().hasHeightForWidth())
        self.bt_add6.setSizePolicy(sizePolicy)
        self.bt_add6.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_add6.setFont(font)
        self.bt_add6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_add6.setAutoFillBackground(False)
        self.bt_add6.setStyleSheet("background-color:#7fc3f2")
        self.bt_add6.setObjectName("bt_add6")
        self.verticalLayout_31.addWidget(self.bt_add6)
        self.bt_remove6 = QtWidgets.QPushButton(self.bt_area6)
        self.bt_remove6.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_remove6.sizePolicy().hasHeightForWidth())
        self.bt_remove6.setSizePolicy(sizePolicy)
        self.bt_remove6.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_remove6.setFont(font)
        self.bt_remove6.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_remove6.setAutoFillBackground(False)
        self.bt_remove6.setStyleSheet("background-color:#7fc3f2")
        self.bt_remove6.setObjectName("bt_remove6")
        self.verticalLayout_31.addWidget(self.bt_remove6)
        self.verticalLayout_31.setStretch(0, 1)
        self.verticalLayout_31.setStretch(1, 1)
        self.horizontalLayout_28.addWidget(self.bt_area6)
        self.horizontalLayout_28.setStretch(0, 4)
        self.verticalLayout_30.addWidget(self.anniu6)
        self.horizontalLayout_27.addWidget(self.operate6)
        self.horizontalLayout_27.setStretch(0, 3)
        self.horizontalLayout_27.setStretch(1, 1)
        self.horizontalLayout_27.setStretch(2, 3)
        self.verticalLayout_35.addWidget(self.team_member6)
        self.team_member7 = QtWidgets.QWidget(self.team2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_member7.sizePolicy().hasHeightForWidth())
        self.team_member7.setSizePolicy(sizePolicy)
        self.team_member7.setStyleSheet("")
        self.team_member7.setObjectName("team_member7")
        self.horizontalLayout_21 = QtWidgets.QHBoxLayout(self.team_member7)
        self.horizontalLayout_21.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_21.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_21.setSpacing(5)
        self.horizontalLayout_21.setObjectName("horizontalLayout_21")
        self.touxiang7 = QtWidgets.QWidget(self.team_member7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touxiang7.sizePolicy().hasHeightForWidth())
        self.touxiang7.setSizePolicy(sizePolicy)
        self.touxiang7.setStyleSheet("")
        self.touxiang7.setObjectName("touxiang7")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.touxiang7)
        self.verticalLayout_8.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_8.setSpacing(5)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.label7 = QtWidgets.QLabel(self.touxiang7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label7.sizePolicy().hasHeightForWidth())
        self.label7.setSizePolicy(sizePolicy)
        self.label7.setText("")
        self.label7.setObjectName("label7")
        self.verticalLayout_8.addWidget(self.label7)
        self.horizontalLayout_21.addWidget(self.touxiang7)
        spacerItem12 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_21.addItem(spacerItem12)
        self.operate7 = QtWidgets.QWidget(self.team_member7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operate7.sizePolicy().hasHeightForWidth())
        self.operate7.setSizePolicy(sizePolicy)
        self.operate7.setStyleSheet("")
        self.operate7.setObjectName("operate7")
        self.verticalLayout_21 = QtWidgets.QVBoxLayout(self.operate7)
        self.verticalLayout_21.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_21.setSpacing(1)
        self.verticalLayout_21.setObjectName("verticalLayout_21")
        spacerItem13 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_21.addItem(spacerItem13)
        self.anniu7 = QtWidgets.QWidget(self.operate7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anniu7.sizePolicy().hasHeightForWidth())
        self.anniu7.setSizePolicy(sizePolicy)
        self.anniu7.setStyleSheet("")
        self.anniu7.setObjectName("anniu7")
        self.horizontalLayout_22 = QtWidgets.QHBoxLayout(self.anniu7)
        self.horizontalLayout_22.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_22.setSpacing(1)
        self.horizontalLayout_22.setObjectName("horizontalLayout_22")
        self.bt_area7 = QtWidgets.QWidget(self.anniu7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_area7.sizePolicy().hasHeightForWidth())
        self.bt_area7.setSizePolicy(sizePolicy)
        self.bt_area7.setStyleSheet("")
        self.bt_area7.setObjectName("bt_area7")
        self.verticalLayout_22 = QtWidgets.QVBoxLayout(self.bt_area7)
        self.verticalLayout_22.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_22.setSpacing(3)
        self.verticalLayout_22.setObjectName("verticalLayout_22")
        self.bt_add7 = QtWidgets.QPushButton(self.bt_area7)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_add7.sizePolicy().hasHeightForWidth())
        self.bt_add7.setSizePolicy(sizePolicy)
        self.bt_add7.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_add7.setFont(font)
        self.bt_add7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_add7.setAutoFillBackground(False)
        self.bt_add7.setStyleSheet("background-color:#7fc3f2")
        self.bt_add7.setObjectName("bt_add7")
        self.verticalLayout_22.addWidget(self.bt_add7)
        self.bt_remove7 = QtWidgets.QPushButton(self.bt_area7)
        self.bt_remove7.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_remove7.sizePolicy().hasHeightForWidth())
        self.bt_remove7.setSizePolicy(sizePolicy)
        self.bt_remove7.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_remove7.setFont(font)
        self.bt_remove7.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_remove7.setAutoFillBackground(False)
        self.bt_remove7.setStyleSheet("background-color:#7fc3f2")
        self.bt_remove7.setObjectName("bt_remove7")
        self.verticalLayout_22.addWidget(self.bt_remove7)
        self.verticalLayout_22.setStretch(0, 1)
        self.verticalLayout_22.setStretch(1, 1)
        self.horizontalLayout_22.addWidget(self.bt_area7)
        self.horizontalLayout_22.setStretch(0, 4)
        self.verticalLayout_21.addWidget(self.anniu7)
        self.horizontalLayout_21.addWidget(self.operate7)
        self.horizontalLayout_21.setStretch(0, 3)
        self.horizontalLayout_21.setStretch(1, 1)
        self.horizontalLayout_21.setStretch(2, 3)
        self.verticalLayout_35.addWidget(self.team_member7)
        self.team_member8 = QtWidgets.QWidget(self.team2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_member8.sizePolicy().hasHeightForWidth())
        self.team_member8.setSizePolicy(sizePolicy)
        self.team_member8.setStyleSheet("")
        self.team_member8.setObjectName("team_member8")
        self.horizontalLayout_23 = QtWidgets.QHBoxLayout(self.team_member8)
        self.horizontalLayout_23.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_23.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_23.setSpacing(5)
        self.horizontalLayout_23.setObjectName("horizontalLayout_23")
        self.touxiang8 = QtWidgets.QWidget(self.team_member8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touxiang8.sizePolicy().hasHeightForWidth())
        self.touxiang8.setSizePolicy(sizePolicy)
        self.touxiang8.setStyleSheet("")
        self.touxiang8.setObjectName("touxiang8")
        self.verticalLayout_23 = QtWidgets.QVBoxLayout(self.touxiang8)
        self.verticalLayout_23.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_23.setSpacing(5)
        self.verticalLayout_23.setObjectName("verticalLayout_23")
        self.label8 = QtWidgets.QLabel(self.touxiang8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label8.sizePolicy().hasHeightForWidth())
        self.label8.setSizePolicy(sizePolicy)
        self.label8.setText("")
        self.label8.setObjectName("label8")
        self.verticalLayout_23.addWidget(self.label8)
        self.horizontalLayout_23.addWidget(self.touxiang8)
        spacerItem14 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_23.addItem(spacerItem14)
        self.operate8 = QtWidgets.QWidget(self.team_member8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operate8.sizePolicy().hasHeightForWidth())
        self.operate8.setSizePolicy(sizePolicy)
        self.operate8.setStyleSheet("")
        self.operate8.setObjectName("operate8")
        self.verticalLayout_24 = QtWidgets.QVBoxLayout(self.operate8)
        self.verticalLayout_24.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_24.setSpacing(1)
        self.verticalLayout_24.setObjectName("verticalLayout_24")
        spacerItem15 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_24.addItem(spacerItem15)
        self.anniu8 = QtWidgets.QWidget(self.operate8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anniu8.sizePolicy().hasHeightForWidth())
        self.anniu8.setSizePolicy(sizePolicy)
        self.anniu8.setStyleSheet("")
        self.anniu8.setObjectName("anniu8")
        self.horizontalLayout_24 = QtWidgets.QHBoxLayout(self.anniu8)
        self.horizontalLayout_24.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_24.setSpacing(1)
        self.horizontalLayout_24.setObjectName("horizontalLayout_24")
        self.bt_area8 = QtWidgets.QWidget(self.anniu8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_area8.sizePolicy().hasHeightForWidth())
        self.bt_area8.setSizePolicy(sizePolicy)
        self.bt_area8.setStyleSheet("")
        self.bt_area8.setObjectName("bt_area8")
        self.verticalLayout_25 = QtWidgets.QVBoxLayout(self.bt_area8)
        self.verticalLayout_25.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_25.setSpacing(3)
        self.verticalLayout_25.setObjectName("verticalLayout_25")
        self.bt_add8 = QtWidgets.QPushButton(self.bt_area8)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_add8.sizePolicy().hasHeightForWidth())
        self.bt_add8.setSizePolicy(sizePolicy)
        self.bt_add8.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_add8.setFont(font)
        self.bt_add8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_add8.setAutoFillBackground(False)
        self.bt_add8.setStyleSheet("background-color:#7fc3f2")
        self.bt_add8.setObjectName("bt_add8")
        self.verticalLayout_25.addWidget(self.bt_add8)
        self.bt_remove8 = QtWidgets.QPushButton(self.bt_area8)
        self.bt_remove8.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_remove8.sizePolicy().hasHeightForWidth())
        self.bt_remove8.setSizePolicy(sizePolicy)
        self.bt_remove8.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_remove8.setFont(font)
        self.bt_remove8.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_remove8.setAutoFillBackground(False)
        self.bt_remove8.setStyleSheet("background-color:#7fc3f2")
        self.bt_remove8.setObjectName("bt_remove8")
        self.verticalLayout_25.addWidget(self.bt_remove8)
        self.verticalLayout_25.setStretch(0, 1)
        self.verticalLayout_25.setStretch(1, 1)
        self.horizontalLayout_24.addWidget(self.bt_area8)
        self.horizontalLayout_24.setStretch(0, 4)
        self.verticalLayout_24.addWidget(self.anniu8)
        self.horizontalLayout_23.addWidget(self.operate8)
        self.horizontalLayout_23.setStretch(0, 3)
        self.horizontalLayout_23.setStretch(1, 1)
        self.horizontalLayout_23.setStretch(2, 3)
        self.verticalLayout_35.addWidget(self.team_member8)
        self.team_member9 = QtWidgets.QWidget(self.team2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_member9.sizePolicy().hasHeightForWidth())
        self.team_member9.setSizePolicy(sizePolicy)
        self.team_member9.setStyleSheet("")
        self.team_member9.setObjectName("team_member9")
        self.horizontalLayout_29 = QtWidgets.QHBoxLayout(self.team_member9)
        self.horizontalLayout_29.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_29.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_29.setSpacing(5)
        self.horizontalLayout_29.setObjectName("horizontalLayout_29")
        self.touxiang9 = QtWidgets.QWidget(self.team_member9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touxiang9.sizePolicy().hasHeightForWidth())
        self.touxiang9.setSizePolicy(sizePolicy)
        self.touxiang9.setStyleSheet("")
        self.touxiang9.setObjectName("touxiang9")
        self.verticalLayout_32 = QtWidgets.QVBoxLayout(self.touxiang9)
        self.verticalLayout_32.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_32.setSpacing(5)
        self.verticalLayout_32.setObjectName("verticalLayout_32")
        self.label9 = QtWidgets.QLabel(self.touxiang9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label9.sizePolicy().hasHeightForWidth())
        self.label9.setSizePolicy(sizePolicy)
        self.label9.setText("")
        self.label9.setObjectName("label9")
        self.verticalLayout_32.addWidget(self.label9)
        self.horizontalLayout_29.addWidget(self.touxiang9)
        spacerItem16 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_29.addItem(spacerItem16)
        self.operate9 = QtWidgets.QWidget(self.team_member9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operate9.sizePolicy().hasHeightForWidth())
        self.operate9.setSizePolicy(sizePolicy)
        self.operate9.setStyleSheet("")
        self.operate9.setObjectName("operate9")
        self.verticalLayout_33 = QtWidgets.QVBoxLayout(self.operate9)
        self.verticalLayout_33.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_33.setSpacing(1)
        self.verticalLayout_33.setObjectName("verticalLayout_33")
        spacerItem17 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_33.addItem(spacerItem17)
        self.anniu9 = QtWidgets.QWidget(self.operate9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anniu9.sizePolicy().hasHeightForWidth())
        self.anniu9.setSizePolicy(sizePolicy)
        self.anniu9.setStyleSheet("")
        self.anniu9.setObjectName("anniu9")
        self.horizontalLayout_30 = QtWidgets.QHBoxLayout(self.anniu9)
        self.horizontalLayout_30.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_30.setSpacing(1)
        self.horizontalLayout_30.setObjectName("horizontalLayout_30")
        self.bt_area9 = QtWidgets.QWidget(self.anniu9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_area9.sizePolicy().hasHeightForWidth())
        self.bt_area9.setSizePolicy(sizePolicy)
        self.bt_area9.setStyleSheet("")
        self.bt_area9.setObjectName("bt_area9")
        self.verticalLayout_34 = QtWidgets.QVBoxLayout(self.bt_area9)
        self.verticalLayout_34.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_34.setSpacing(3)
        self.verticalLayout_34.setObjectName("verticalLayout_34")
        self.bt_add9 = QtWidgets.QPushButton(self.bt_area9)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_add9.sizePolicy().hasHeightForWidth())
        self.bt_add9.setSizePolicy(sizePolicy)
        self.bt_add9.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_add9.setFont(font)
        self.bt_add9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_add9.setAutoFillBackground(False)
        self.bt_add9.setStyleSheet("background-color:#7fc3f2")
        self.bt_add9.setObjectName("bt_add9")
        self.verticalLayout_34.addWidget(self.bt_add9)
        self.bt_remove9 = QtWidgets.QPushButton(self.bt_area9)
        self.bt_remove9.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_remove9.sizePolicy().hasHeightForWidth())
        self.bt_remove9.setSizePolicy(sizePolicy)
        self.bt_remove9.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_remove9.setFont(font)
        self.bt_remove9.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_remove9.setAutoFillBackground(False)
        self.bt_remove9.setStyleSheet("background-color:#7fc3f2")
        self.bt_remove9.setObjectName("bt_remove9")
        self.verticalLayout_34.addWidget(self.bt_remove9)
        self.verticalLayout_34.setStretch(0, 1)
        self.verticalLayout_34.setStretch(1, 1)
        self.horizontalLayout_30.addWidget(self.bt_area9)
        self.horizontalLayout_30.setStretch(0, 4)
        self.verticalLayout_33.addWidget(self.anniu9)
        self.horizontalLayout_29.addWidget(self.operate9)
        self.horizontalLayout_29.setStretch(0, 3)
        self.horizontalLayout_29.setStretch(1, 1)
        self.horizontalLayout_29.setStretch(2, 3)
        self.verticalLayout_35.addWidget(self.team_member9)
        self.team_member10 = QtWidgets.QWidget(self.team2)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.team_member10.sizePolicy().hasHeightForWidth())
        self.team_member10.setSizePolicy(sizePolicy)
        self.team_member10.setStyleSheet("")
        self.team_member10.setObjectName("team_member10")
        self.horizontalLayout_25 = QtWidgets.QHBoxLayout(self.team_member10)
        self.horizontalLayout_25.setSizeConstraint(QtWidgets.QLayout.SetNoConstraint)
        self.horizontalLayout_25.setContentsMargins(5, 5, 5, 5)
        self.horizontalLayout_25.setSpacing(5)
        self.horizontalLayout_25.setObjectName("horizontalLayout_25")
        self.touxiang10 = QtWidgets.QWidget(self.team_member10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.touxiang10.sizePolicy().hasHeightForWidth())
        self.touxiang10.setSizePolicy(sizePolicy)
        self.touxiang10.setStyleSheet("")
        self.touxiang10.setObjectName("touxiang10")
        self.verticalLayout_26 = QtWidgets.QVBoxLayout(self.touxiang10)
        self.verticalLayout_26.setContentsMargins(5, 5, 5, 5)
        self.verticalLayout_26.setSpacing(5)
        self.verticalLayout_26.setObjectName("verticalLayout_26")
        self.label10 = QtWidgets.QLabel(self.touxiang10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label10.sizePolicy().hasHeightForWidth())
        self.label10.setSizePolicy(sizePolicy)
        self.label10.setText("")
        self.label10.setObjectName("label10")
        self.verticalLayout_26.addWidget(self.label10)
        self.horizontalLayout_25.addWidget(self.touxiang10)
        spacerItem18 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_25.addItem(spacerItem18)
        self.operate10 = QtWidgets.QWidget(self.team_member10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.operate10.sizePolicy().hasHeightForWidth())
        self.operate10.setSizePolicy(sizePolicy)
        self.operate10.setStyleSheet("")
        self.operate10.setObjectName("operate10")
        self.verticalLayout_27 = QtWidgets.QVBoxLayout(self.operate10)
        self.verticalLayout_27.setContentsMargins(1, 1, 1, 1)
        self.verticalLayout_27.setSpacing(1)
        self.verticalLayout_27.setObjectName("verticalLayout_27")
        spacerItem19 = QtWidgets.QSpacerItem(20, 40, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout_27.addItem(spacerItem19)
        self.anniu10 = QtWidgets.QWidget(self.operate10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.anniu10.sizePolicy().hasHeightForWidth())
        self.anniu10.setSizePolicy(sizePolicy)
        self.anniu10.setStyleSheet("")
        self.anniu10.setObjectName("anniu10")
        self.horizontalLayout_26 = QtWidgets.QHBoxLayout(self.anniu10)
        self.horizontalLayout_26.setContentsMargins(1, 1, 1, 1)
        self.horizontalLayout_26.setSpacing(1)
        self.horizontalLayout_26.setObjectName("horizontalLayout_26")
        self.bt_area10 = QtWidgets.QWidget(self.anniu10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_area10.sizePolicy().hasHeightForWidth())
        self.bt_area10.setSizePolicy(sizePolicy)
        self.bt_area10.setStyleSheet("")
        self.bt_area10.setObjectName("bt_area10")
        self.verticalLayout_28 = QtWidgets.QVBoxLayout(self.bt_area10)
        self.verticalLayout_28.setContentsMargins(1, 3, 1, 3)
        self.verticalLayout_28.setSpacing(3)
        self.verticalLayout_28.setObjectName("verticalLayout_28")
        self.bt_add10 = QtWidgets.QPushButton(self.bt_area10)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_add10.sizePolicy().hasHeightForWidth())
        self.bt_add10.setSizePolicy(sizePolicy)
        self.bt_add10.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_add10.setFont(font)
        self.bt_add10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_add10.setAutoFillBackground(False)
        self.bt_add10.setStyleSheet("background-color:#7fc3f2")
        self.bt_add10.setObjectName("bt_add10")
        self.verticalLayout_28.addWidget(self.bt_add10)
        self.bt_remove10 = QtWidgets.QPushButton(self.bt_area10)
        self.bt_remove10.setEnabled(False)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.bt_remove10.sizePolicy().hasHeightForWidth())
        self.bt_remove10.setSizePolicy(sizePolicy)
        self.bt_remove10.setMinimumSize(QtCore.QSize(3, 1))
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setItalic(False)
        font.setWeight(75)
        font.setStrikeOut(False)
        self.bt_remove10.setFont(font)
        self.bt_remove10.setCursor(QtGui.QCursor(QtCore.Qt.PointingHandCursor))
        self.bt_remove10.setAutoFillBackground(False)
        self.bt_remove10.setStyleSheet("background-color:#7fc3f2")
        self.bt_remove10.setObjectName("bt_remove10")
        self.verticalLayout_28.addWidget(self.bt_remove10)
        self.verticalLayout_28.setStretch(0, 1)
        self.verticalLayout_28.setStretch(1, 1)
        self.horizontalLayout_26.addWidget(self.bt_area10)
        self.horizontalLayout_26.setStretch(0, 4)
        self.verticalLayout_27.addWidget(self.anniu10)
        self.horizontalLayout_25.addWidget(self.operate10)
        self.horizontalLayout_25.setStretch(0, 3)
        self.horizontalLayout_25.setStretch(1, 1)
        self.horizontalLayout_25.setStretch(2, 3)
        self.verticalLayout_35.addWidget(self.team_member10)
        self.verticalLayout_35.setStretch(0, 1)
        self.verticalLayout_35.setStretch(1, 1)
        self.verticalLayout_35.setStretch(2, 1)
        self.verticalLayout_35.setStretch(3, 1)
        self.verticalLayout_35.setStretch(4, 1)
        self.horizontalLayout.addWidget(self.team2)
        self.horizontalLayout.setStretch(0, 2)
        self.horizontalLayout.setStretch(1, 1)
        self.horizontalLayout.setStretch(2, 2)
        self.team2.raise_()
        self.team1.raise_()
        self.start_panel.raise_()
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 700, 26))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.menubar.sizePolicy().hasHeightForWidth())
        self.menubar.setSizePolicy(sizePolicy)
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(self.menubar)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.menu.setFont(font)
        self.menu.setObjectName("menu")
        self.menu_2 = QtWidgets.QMenu(self.menubar)
        self.menu_2.setObjectName("menu_2")
        MainWindow.setMenuBar(self.menubar)
        self.statusBar = QtWidgets.QStatusBar(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.statusBar.setFont(font)
        self.statusBar.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.statusBar.setStyleSheet("background-color:white")
        self.statusBar.setObjectName("statusBar")
        MainWindow.setStatusBar(self.statusBar)
        self.start_simulator = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.start_simulator.setFont(font)
        self.start_simulator.setObjectName("start_simulator")
        self.save_team_data = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.save_team_data.setFont(font)
        self.save_team_data.setObjectName("save_team_data")
        self.load_team_data = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.load_team_data.setFont(font)
        self.load_team_data.setObjectName("load_team_data")
        self.exit_program = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.exit_program.setFont(font)
        self.exit_program.setObjectName("exit_program")
        self.help_information = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.help_information.setFont(font)
        self.help_information.setObjectName("help_information")
        self.soft_info = QtWidgets.QAction(MainWindow)
        font = QtGui.QFont()
        font.setFamily("微软雅黑")
        font.setBold(True)
        font.setWeight(75)
        self.soft_info.setFont(font)
        self.soft_info.setObjectName("soft_info")
        self.menu.addAction(self.start_simulator)
        self.menu.addSeparator()
        self.menu.addAction(self.save_team_data)
        self.menu.addAction(self.load_team_data)
        self.menu.addSeparator()
        self.menu.addAction(self.exit_program)
        self.menu_2.addAction(self.help_information)
        self.menu_2.addAction(self.soft_info)
        self.menubar.addAction(self.menu.menuAction())
        self.menubar.addAction(self.menu_2.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.bt_add1.setText(_translate("MainWindow", "添加式神"))
        self.bt_remove1.setText(_translate("MainWindow", "删除式神"))
        self.bt_add2.setText(_translate("MainWindow", "添加式神"))
        self.bt_remove2.setText(_translate("MainWindow", "删除式神"))
        self.bt_add3.setText(_translate("MainWindow", "添加式神"))
        self.bt_remove3.setText(_translate("MainWindow", "删除式神"))
        self.bt_add4.setText(_translate("MainWindow", "添加式神"))
        self.bt_remove4.setText(_translate("MainWindow", "删除式神"))
        self.bt_add5.setText(_translate("MainWindow", "添加式神"))
        self.bt_remove5.setText(_translate("MainWindow", "删除式神"))
        self.start_sim.setText(_translate("MainWindow", "开始模拟"))
        self.bt_add6.setText(_translate("MainWindow", "添加式神"))
        self.bt_remove6.setText(_translate("MainWindow", "删除式神"))
        self.bt_add7.setText(_translate("MainWindow", "添加式神"))
        self.bt_remove7.setText(_translate("MainWindow", "删除式神"))
        self.bt_add8.setText(_translate("MainWindow", "添加式神"))
        self.bt_remove8.setText(_translate("MainWindow", "删除式神"))
        self.bt_add9.setText(_translate("MainWindow", "添加式神"))
        self.bt_remove9.setText(_translate("MainWindow", "删除式神"))
        self.bt_add10.setText(_translate("MainWindow", "添加式神"))
        self.bt_remove10.setText(_translate("MainWindow", "删除式神"))
        self.menu.setTitle(_translate("MainWindow", "菜单"))
        self.menu_2.setTitle(_translate("MainWindow", "帮助"))
        self.start_simulator.setText(_translate("MainWindow", "开始模拟"))
        self.save_team_data.setText(_translate("MainWindow", "保存阵容"))
        self.load_team_data.setText(_translate("MainWindow", "读取阵容"))
        self.exit_program.setText(_translate("MainWindow", "退出程序"))
        self.help_information.setText(_translate("MainWindow", "使用方法"))
        self.soft_info.setText(_translate("MainWindow", "关于软件"))

